"""data table

Revision ID: 27390d33891d
Revises: 
Create Date: 2021-06-28 14:03:14.003416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27390d33891d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetimeRegister', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_row_datetimeRegister'), 'data_row', ['datetimeRegister'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_row_datetimeRegister'), table_name='data_row')
    op.drop_table('data_row')
    # ### end Alembic commands ###
